apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
# Here noauth overlay is using the same image as stable-master
transformers:
- ../../images/stable-master
patchesStrategicMerge:
- noauth.yaml
namespace: gce-pd-csi-driver
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: us-central1-docker.pkg.dev/songsunny-gke-dev2/csi-dev/gcp-compute-persistent-disk-csi-driver
  newTag: latest

